version: "3.2"

# Extends docker-common.yml

services:

  # Talks API
  server:
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - DATABASE_DEBUG=false
      - NODE_DEBUG=true
    ports:
      - "9229:9229" # V8 inspector (when NODE_DEBUG=true)
    command: node --inspect=172.28.0.3:9229 dist/server/index.js
    networks:
      service_net:
        ipv4_address: 172.28.0.3

  # SQL database
  db:
    image: postgres:9.6.3-alpine
    read_only: true
    environment:
      - POSTGRES_USER=postgres
    networks:
      service_net:
        ipv4_address: 172.28.0.2

networks:

  service_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16  