version: "3.2"

services:

    # Talks API server
    server:
        image: node:8.1.2-alpine
        hostname: talks_api
        depends_on:
            - db
        expose:
            - "8080"
        volumes:
            - yarn:/root/.cache/yarn
            - ./:/usr/src/app
        user: node
        working_dir: /usr/src/app

    # SQL database
    db:
        image: postgres:9.6.3-alpine
        tmpfs:
            - /tmp
            - /var/run/postgresql
        volumes:
            - db:/var/lib/postgresql/data
            - ./db/config/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

volumes:
  yarn:
  db: